# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "redismaster" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "redismaster"
    node.vm.network "private_network", ip: "192.168.33.10"

    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "redismaster"
      vb.memory = "2046"
    end
  end

(1..2).each do |i|
  config.vm.define "redisslave#{i}" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "redisslave#{i}"
    node.vm.network "private_network", ip: "192.168.33.1#{i}"

    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "redisslave#{i}"
      vb.memory = "1024"
    end
    end
  end
end

